# docker-compose up --exit-code-from elasticsearch_tester
version: '3'
services:
  rasa:
    image: yuriowindiatmoko2401/rasa-chatbot-uii-1:v.0.4-GRU-128
    ports:
      - "5002:5002"
      - "5005:5005"
      # http://localhost:5002/api
    depends_on:
      - action_server
    command:
      - rasa 
      - run 
      - --model
      - /usr/workspace/models/GRU_128_rnn_size.tar.gz
      - --enable-api 
      - --cors 
      - "*" 
      - --port 
      - "5005" 
      - --debug
  action_server:
    image: yuriowindiatmoko2401/rasa-chatbot-uii-1:v.0.4-GRU-128
    environment:
      - MYSQL_HOST=some-mariadb
    ports:
      - "5055:5055"
    depends_on:
      - some-mariadb
    command:
      - rasa 
      - run 
      - actions 
      - --port 
      - "5055" 
      - --debug
  some-mariadb:
    image: mariadb 
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
